// Miscellaneous utilities for solver apps which do not fit into any other category.

syntax = "proto3";

package ansys.api.fluent.v0.app_utilities;

service AppUtilities {
  /* Get product version */
  rpc GetProductVersion(GetProductVersionRequest) returns (GetProductVersionResponse);

  /* Get build information */
  rpc GetBuildInfo(GetBuildInfoRequest) returns (GetBuildInfoResponse);

  /**
   * Get Controller process information if the solver app is running in client-server mode,
   * Controller process commanding the Solver process.
   */
  rpc GetControllerProcessInfo(GetControllerProcessInfoRequest) returns (GetControllerProcessInfoResponse);

  /* Get Solver process information */
  rpc GetSolverProcessInfo(GetSolverProcessInfoRequest) returns (GetSolverProcessInfoResponse);

  /* Get App mode */
  rpc GetAppMode(GetAppModeRequest) returns (GetAppModeResponse);

  /* Start Python journal */
  rpc StartPythonJournal(StartPythonJournalRequest) returns (StartPythonJournalResponse);

  /* Stop Python journal */
  rpc StopPythonJournal(StopPythonJournalRequest) returns (StopPythonJournalResponse);

  /* Is beta feature enabled? */
  rpc IsBetaEnabled(IsBetaEnabledRequest) returns (IsBetaEnabledResponse);

  /* Is wildcard as per the solver app's syntax? */
  rpc IsWildcard(IsWildcardRequest) returns (IsWildcardResponse);

  /* Is solution data available? */
  rpc IsSolutionDataAvailable(IsSolutionDataAvailableRequest) returns (IsSolutionDataAvailableResponse);

  /**
   * Following 3 methods are useful to execute synchronous callbacks in gRPC client on solution events
   * such as iteration or time-step advancement. An implementation of such mechanism will look like:
   * 1. After each solution event, the solver will send a paused event to clients and pause itself.
   * 2. The registered client will receive the paused event and execute the callback and then resume the solver.
   *
   * Register to pause on solution events.
   */
  rpc RegisterPauseOnSolutionEvents(RegisterPauseOnSolutionEventsRequest) returns (RegisterPauseOnSolutionEventsResponse);

  /* Resume from pause on a solution event */
  rpc ResumeOnSolutionEvent(ResumeOnSolutionEventRequest) returns (ResumeOnSolutionEventResponse);

  /* Unregister to pause on solution events */
  rpc UnregisterPauseOnSolutionEvents(UnregisterPauseOnSolutionEventsRequest) returns (UnregisterPauseOnSolutionEventsResponse);

  /* Exit the solver app */
  rpc Exit(ExitRequest) returns (ExitResponse);
}

message GetProductVersionRequest {
}

message GetProductVersionResponse {
  /* Major version */
  int64 major = 1;
  /* Minor version */
  int64 minor = 2;
  /* Patch version */
  int64 patch = 3;
}

message GetBuildInfoRequest {
}

message GetBuildInfoResponse {
  /* Build time */
  string build_time = 1;
  /* Build id */
  int64 build_id = 2;
  /* VCS revision */
  string vcs_revision = 3;
  /* VCS branch */
  string vcs_branch = 4;
}

message GetControllerProcessInfoRequest {
}

message GetControllerProcessInfoResponse {
  /* Controller hostname */
  string hostname = 1;
  /* Controller process id */
  int64 process_id = 2;
  /* Controller working directory */
  string working_directory = 3;
}

message GetSolverProcessInfoRequest {
}

message GetSolverProcessInfoResponse {
  /* Solver hostname */
  string hostname = 1;
  /* Solver process id */
  int64 process_id = 2;
  /* Solver working directory */
  string working_directory = 3;
}

message GetAppModeRequest {
}

message GetAppModeResponse {
  /* App mode */
  AppMode app_mode = 1;
}

message StartPythonJournalRequest {
  /**
   * Journal file name
   * If journal_name is not provided, StopPythonJournal should return the journal lines.
   */
  optional string journal_name = 1;
}

message StartPythonJournalResponse {
  /**
   * Journal id
   * Journal id is returned if journal_name is not provided.
   */
  optional string journal_id = 1;
}

message StopPythonJournalRequest {
  /**
   * Journal id
   * Journal id is required if journal_name is not provided in StartPythonJournal.
   */
  optional string journal_id = 1;
}

message StopPythonJournalResponse {
  /**
   * Journal lines
   * Journal lines are returned if journal_name is not provided in StartPythonJournal.
   */
  string journal_str = 1;
}

message IsBetaEnabledRequest {
}

message IsBetaEnabledResponse {
  /* Is beta feature enabled */
  bool is_beta_enabled = 1;
}

message IsWildcardRequest {
  /* String to check if it is a wildcard */
  string input = 1;
}

message IsWildcardResponse {
  /* Is wildcard */
  bool is_wildcard = 1;
}

message IsSolutionDataAvailableRequest {
}

message IsSolutionDataAvailableResponse {
  /* Is solution data available */
  bool is_solution_data_available = 1;
}

message RegisterPauseOnSolutionEventsRequest {
  /* Solution event */
  SolutionEvent solution_event = 1;
}

message RegisterPauseOnSolutionEventsResponse {
  /* Registration id */
  string registration_id = 1;
}

message ResumeOnSolutionEventRequest {
  /* Registration id */
  string registration_id = 1;
}

message ResumeOnSolutionEventResponse {
}

message UnregisterPauseOnSolutionEventsRequest {
  /* Registration id */
  string registration_id = 1;
}

message UnregisterPauseOnSolutionEventsResponse {
}

message ExitRequest {
}

message ExitResponse {
}

enum AppMode {
  /* App mode unknown */
  APP_MODE_UNKNOWN = 0;
  /* App mode meshing */
  APP_MODE_MESHING = 1;
  /* App mode solver */
  APP_MODE_SOLVER = 2;
  /* App mode icing */
  APP_MODE_SOLVER_ICING = 3;
  /* App mode aero */
  APP_MODE_SOLVER_AERO = 4;
}

enum SolutionEvent {
  /* Solution event unknown */
  SOLUTION_EVENT_UNKNOWN = 0;
  /* Solution event iteration */
  SOLUTION_EVENT_ITERATION = 1;
  /* Solution event time step */
  SOLUTION_EVENT_TIME_STEP = 2;
}
