// Copyright (C) 2021 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
//
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

syntax = "proto3";

package ansys.api.fluent.v0;

import "google/protobuf/struct.proto";

service DataModel {
  rpc NotifyChanges(NotifyChangesRequest) returns (stream NotifyChangesResponse);

  rpc GetAttributeValue(GetAttributeValueRequest) returns (GetAttributeValueResponse);
  rpc GetState(GetStateRequest) returns (GetStateResponse);
  rpc SetState(SetStateRequest) returns (SetStateResponse);
  rpc ExecuteCommand(ExecuteCommandRequest) returns (ExecuteCommandResponse);
  rpc ExecuteQuery(ExecuteQueryRequest) returns (ExecuteQueryResponse);

  rpc CompositeGet(CompositeGetRequest) returns (CompositeGetResponse);

  rpc GetStaticInfo(GetStaticInfoRequest) returns (GetStaticInfoResponse) {};
}

message NotifyChangesRequest {
  google.protobuf.Value paths = 1;
  google.protobuf.Struct args = 2;
}

message NotifyChangesResponse {
  google.protobuf.Value changed_paths = 1;
  google.protobuf.Value state_difference = 2;
}

enum Attribute {
  // Static attributes
  CHILD_NAMES = 0;
  DATA_TYPE = 1;
  EXPOSURE_LEVEL = 2;
  DISPLAY_TEXT = 3;
  QUANTITY_TYPE = 4;
  HELP_STRING = 5;

  // Dynamic attributes
  DEFAULT = 100;
  ALLOWED_VALUES = 101;
  MINIMUM = 102;
  MAXIMUM = 103;
  IS_ACTIVE = 104;
  IS_READ_ONLY = 105;
  OBJECT_NAMES = 106;

  // Composite attributes
  CONSTRAINTS = 200;
  STATIC_ATTRIBUTES = 201;
  UI_ATTRIBUTES = 202;

  // Custom attribute
  CUSTOM = 300;
}

message GetAttributeValueRequest {
  string path = 1;
  Attribute attribute = 2;
  google.protobuf.Struct args = 3;
}

message GetAttributeValueResponse {
  google.protobuf.Value value = 1;
}

message GetStateRequest {
  string path = 1;
}

message GetStateResponse {
  google.protobuf.Value state = 1;
}

message SetStateRequest {
  string path = 1;
  google.protobuf.Value state = 2;
}

message SetStateResponse {
  google.protobuf.Value state = 1;
}

message ExecuteCommandRequest {
  string path = 1;
  string command = 2;
  google.protobuf.Struct args = 3;
}

message ExecuteCommandResponse {
  google.protobuf.Value result = 1;
}

message ExecuteQueryRequest {
  string path = 1;
}

message ExecuteQueryResponse {
  google.protobuf.Value result = 1;
}

message CompositeGetRequest {
  repeated DataModelGetter getters = 1;
}

message DataModelGetter {
  oneof request {
    GetAttributeValueRequest get_attribute_value_request = 1;
    GetStateRequest get_state_request = 2;
  }
}

message CompositeGetResponse {
  google.protobuf.Value response = 1;
}

message GetStaticInfoRequest {
  string path = 1;
}

message StaticInfo {
  map<string, StaticInfo> menus = 1;
  map<string, StaticInfo> commands = 2;
  string help = 5;
}

message GetStaticInfoResponse {
  StaticInfo info = 1;
}
