//
// Copyright 1987-2022 ANSYS, Inc. All Rights Reserved.
//

syntax = "proto3";

package grpcRemoting;

import "ansys/api/fluent/v0/variant.proto";

service DataModel {
  rpc BeginStreaming(DataModelRequest) returns (stream DataModelResponse) {}

  rpc initDatamodel(InitDatamodelRequest) returns (InitDatamodelResponse) {}
  rpc getState(GetStateRequest) returns (GetStateResponse) {}
  rpc setState(SetStateRequest) returns (SetStateResponse) {}
  rpc updateDict(UpdateDictRequest) returns (UpdateDictResponse) {}
  rpc deleteObject(DeleteObjectRequest) returns (DeleteObjectResponse) {}
  rpc getAttributeValue(GetAttributeValueRequest) returns (GetAttributeValueResponse) {}
  rpc executeCommand(ExecuteCommandRequest) returns (ExecuteCommandResponse) {}
  rpc createCommandArguments(CreateCommandArgumentsRequest) returns (CreateCommandArgumentsResponse) {}
  rpc deleteCommandArguments(DeleteCommandArgumentsRequest) returns (DeleteCommandArgumentsResponse) {}
  rpc getSpecs(GetSpecsRequest) returns (GetSpecsResponse) {}
  rpc getStaticInfo(GetStaticInfoRequest) returns (GetStaticInfoResponse) {}

  // Subscribe to datamodel events
  rpc subscribeEvents(SubscribeEventsRequest) returns (SubscribeEventsResponse) {}

  // Request streaming of previously subscribed events
  rpc unsubscribeEvents(UnsubscribeEventsRequest) returns (UnsubscribeEventsResponse) {}

  // Unsubscribe previously subscribed events
  rpc BeginEventStreaming(EventRequest) returns (stream EventResponse) {}
}

enum DiffState {
  DIFFSTATE_FULL = 0;
  DIFFSTATE_NOCOMMANDS = 1;
}

message DataModelRequest {
  string rules = 1;
  bool returnstatechanges = 2;
  DiffState diffstate = 3;
}

message DataModelResponse {
  utils.Variant state = 1;
  repeated string deletedpaths = 2;
  repeated string events = 3;
}

message InitDatamodelRequest {
  string rules = 1;
  bool returnstatechanges = 2;
}

message InitDatamodelResponse {
  utils.Variant state = 1;
  repeated string deletedpaths = 2;
}

message GetStateRequest {
  string rules = 1;
  string path = 2;
}

message GetStateResponse {
  utils.Variant state = 1;
}

message SetStateRequest {
  string rules = 1;
  string path = 2;
  utils.Variant state = 3;
  bool wait = 4;
}

message SetStateResponse {
  utils.Variant state = 1;
  repeated string deletedpaths = 2;
}

message UpdateDictRequest {
  string rules = 1;
  string path = 2;
  utils.Variant dicttomerge = 3;
  bool wait = 4;
}

message UpdateDictResponse {
  utils.Variant state = 1;
  repeated string deletedpaths = 2;
}

message DeleteObjectRequest {
  string rules = 1;
  string path = 2;
  bool wait = 3;
}

message DeleteObjectResponse {
  utils.Variant state = 1;
  repeated string deletedpaths = 2;
}

message GetAttributeValueRequest {
  string rules = 1;
  string path = 2;
  string attribute = 3;
}

message GetAttributeValueResponse {
  utils.Variant result = 1;
}

message ExecuteCommandRequest {
  string rules = 1;
  string path = 2;
  string command = 3;
  bool wait = 4;
  utils.Variant args = 5;
}

message ExecuteCommandResponse {
  utils.Variant result = 1;
  utils.Variant state = 2;
  repeated string deletedpaths = 3;
}

message CreateCommandArgumentsRequest {
  string rules = 1;
  string path = 2;
  string command = 3;
}

message CreateCommandArgumentsResponse {
  string commandid = 1;
}

message DeleteCommandArgumentsRequest {
  string rules = 1;
  string path = 2;
  string command = 3;
  string commandid = 4;
}

message DeleteCommandArgumentsResponse {
}

message GetSpecsRequest {
  string rules = 1;
  string path = 2;
  bool includeChildren = 3;
}

message CommonSpecs {
  bool readonly = 1;
  utils.Variant default = 2;
  string displaytext = 3;
  bool isactive = 4;
  string referencepath = 5;
  bool hasDeveloperExposureLevel = 6;
  string helpstring = 7;
}

message BoolParameterSpecs {
  CommonSpecs common = 1;
}

message IntParameterSpecs {
  CommonSpecs common = 1;
  oneof il {
    int32 lowerbound = 2;
  }
  oneof iu {
    int32 upperbound = 3;
  }
}

message RealParameterSpecs {
  CommonSpecs common = 1;
  oneof rl {
    double lowerbound = 2;
  }
  oneof ru {
    double upperbound = 3;
  }
}

message StringParameterSpecs {
  CommonSpecs common = 1;
  repeated string allowedstringlist = 2;
}

message IntListParameterSpecs {
  CommonSpecs common = 1;
}

message StringListParameterSpecs {
  CommonSpecs common = 1;
  repeated string allowedstringlist = 2;
}

message CommandSpecs {
  string name = 1;
  bool isactive = 2;
}

message SingletonSpecs {
  CommonSpecs common = 1;
  repeated string members = 2;
  repeated CommandSpecs commands = 3;
  repeated string creatabletypes = 4;
}

message NamedObjectSpecs {
  CommonSpecs common = 1;
  repeated string members = 2;
  repeated CommandSpecs commands = 3;
  repeated string creatabletypes = 4;
}

message MemberSpecs {
  string name = 1;
  string type = 2;
  oneof as {
    BoolParameterSpecs bool = 3;
    IntParameterSpecs int = 4;
    RealParameterSpecs real = 5;
    StringParameterSpecs string = 6;
    IntListParameterSpecs intlist = 7;
    StringListParameterSpecs stringlist = 8;
    SingletonSpecs singleton = 9;
    NamedObjectSpecs namedobject = 10;
  }
  repeated MemberSpecs children = 11;
}

message GetSpecsResponse {
  MemberSpecs member = 1;
}

message CommandArg {
  string type = 1;
  string name = 2;
  StaticInfo info = 3;
}

message CommandInfo {
  string returntype = 1;
  repeated CommandArg args = 2;
}

message StaticInfo {
  map<string, StaticInfo> namedobjects = 1;
  map<string, StaticInfo> singletons = 2;
  map<string, StaticInfo> parameters = 3;
  map<string, StaticInfo> commands = 4;
  string type = 5;
  CommandInfo commandinfo = 6;
}

message GetStaticInfoRequest {
  string rules = 1;
}

message GetStaticInfoResponse {
  StaticInfo info = 1;
}

message CreatedEventRequest {
  string parentpath = 1;  // parent-path of the created object
  string childtype = 2;   // type of the created object
}

message ModifiedEventRequest {
  string path = 1;  // path of the modified object
}

message DeletedEventRequest {
  string path = 1;  // path of the deleted object
}

message AffectedEventRequest {
  string path = 1;  // path of the affected object
  string subtype = 2;
}

message AttributeChangedEventRequest {
  string path = 1;       // path of the object whose attribute is changed
  string attribute = 2;  // name of the attribute
}

message CommandAttributeChangedEventRequest {
  string path = 1;       // path of the object whose command attribute is changed
  string command = 2;    // name of the command
  string attribute = 3;  // name of the attribute
}

message CommandExecutedEventRequest {
  string path = 1;     // path of the object with the command
  string command = 2;  // name of the command
}

message DataModelEventRequest {
  string rules = 1;
  oneof eventrequest {
    CreatedEventRequest createdEventRequest = 2;
    ModifiedEventRequest modifiedEventRequest = 3;
    DeletedEventRequest deletedEventRequest = 4;
    AffectedEventRequest affectedEventRequest = 5;
    AttributeChangedEventRequest attributeChangedEventRequest = 6;
    CommandAttributeChangedEventRequest commandAttributeChangedEventRequest = 7;
    CommandExecutedEventRequest commandExecutedEventRequest = 8;
  }
}

message SubscribeEventsRequest {
  repeated DataModelEventRequest eventrequest = 1;
}

enum SubscriptionStatus {
  STATUS_UNSPECIFIED = 0;
  STATUS_SUBSCRIBED = 1;
  STATUS_UNSUBSCRIBED = 2;
}

message EventSubscription {
  // tag is used to identify a subscribed event in server.
  // A subscribed event can later be unsubscribed.
  string tag = 1;
  SubscriptionStatus status = 2;
}

message SubscribeEventsResponse {
  repeated EventSubscription response = 1;
}

message UnsubscribeEventsRequest {
  repeated string tag = 1;
}

message UnsubscribeEventsResponse {
  repeated EventSubscription response = 1;
}

message EventRequest {
}

message CreatedEventResponse {
  string parentpath = 1;  // parent-path of the created object
  string childtype = 2;   // type of the created object
  string childname = 3;   // name of the created object
}

message ModifiedEventResponse {
  string path = 1;          // path of the modified object
  utils.Variant value = 2;  // value of the modified object
}

message DeletedEventResponse {
  string path = 1;  // path of the deleted object
}

message AffectedEventResponse {
  string path = 1;  // path of the affected object
  string subtype = 2;
}

message AttributeChangedEventResponse {
  string path = 1;          // path of the object whose attribute is changed
  string attribute = 2;     // name of the attribute
  utils.Variant value = 3;  // value of the attribute
}

message CommandAttributeChangedEventResponse {
  string path = 1;          // path of the object whose command attribute is changed
  string command = 2;       // name of the command
  string attribute = 3;     // name of the attribute
  utils.Variant value = 4;  // value of the attribute
}

message CommandExecutedEventResponse {
  string path = 1;         // path of the object with the command
  string command = 2;      // name of the command
  utils.Variant args = 3;  // command arguments
}

message EventResponse {
  string tag = 1;
  string rules = 2;
  oneof eventresponse {
    CreatedEventResponse createdEventResponse = 3;
    ModifiedEventResponse modifiedEventResponse = 4;
    DeletedEventResponse deletedEventResponse = 5;
    AffectedEventResponse affectedEventResponse = 6;
    AttributeChangedEventResponse attributeChangedEventResponse = 7;
    CommandAttributeChangedEventResponse commandAttributeChangedEventResponse = 8;
    CommandExecutedEventResponse commandExecutedEventResponse = 9;
  }
}
