//
// Copyright 1987-2022 ANSYS, Inc. All Rights Reserved.
//

syntax = "proto3";

package grpcRemoting;

import "ansys/api/fluent/v0/scheme_pointer.proto";

service Events {
  rpc BeginStreaming(BeginStreamingRequest) returns (stream BeginStreamingResponse) {}
}

message TimestepStartedEvent {
  sint64 index = 1;  // Time step index
  double size = 2;   // Time step size.
}

message TimestepEndedEvent {
  sint64 index = 1;  // Time step index
  double size = 2;   // Time step size.
}

message IterationStartedEvent {
  sint64 index = 1;  // Iteration index
}
message IterationEndedEvent {
  sint64 index = 1;  // Iteration index
}

message CalculationsStartedEvent {
}
message CalculationsEndedEvent {
}

message CalculationsPausedEvent {
}
message CalculationsResumedEvent {
}

message AboutToReadCaseEvent {
  string casefilepath = 1;  // Case file path
}
message CaseReadEvent {
  string casefilepath = 1;  // Case file path
}

message AboutToReadDataEvent {
  string datafilepath = 1;  // Data file path
}
message DataReadEvent {
  string datafilepath = 1;  // Data file path
}

message AboutToInitializeEvent {
}

message InitializedEvent {
}

message ReportDefinitionChangedEvent {
  string reportdefinitionname = 1;
}

message PlotSetChangedEvent {
  string plotsetname = 1;
}

message ResidualPlotChangedEvent {
}

message ClearSettingsDoneEvent {
}

message AutoPauseEvent {
  sint32 level = 1;
  sint64 index = 2;
}

message ProgressEvent {
  string message = 1;          // Progress Message
  sint32 percentComplete = 2;  // Percent completed
}

message SolverTimeEstimateEvent {
  double hours = 1;
  double minutes = 2;
  double seconds = 3;
}

/*
 * Event when fatal error encountered
 */
message ErrorEvent {
  string message = 1;
  sint32 errorCode = 2;
}

message CommandCompletedEvent {
}

message BeginStreamingRequest {
}

message DataModelChangedEvent {
  repeated string paths = 1;
}

message ExecuteInClientEvent {
  string function = 1;
  repeated SchemePointer arguments = 2;
}

message BeginStreamingResponse {
  oneof as {
    AboutToReadCaseEvent abouttoreadcaseevent = 1;
    CaseReadEvent casereadevent = 2;

    AboutToInitializeEvent abouttoinitializeevent = 3;
    InitializedEvent initializedevent = 4;

    AboutToReadDataEvent abouttoreaddataevent = 5;
    DataReadEvent datareadevent = 6;

    IterationStartedEvent iterationstartedevent = 7;
    IterationEndedEvent iterationendedevent = 8;

    TimestepStartedEvent timestepstartedevent = 9;
    TimestepEndedEvent timestependedevent = 10;

    CalculationsStartedEvent calculationsstartedevent = 11;
    CalculationsEndedEvent calculationsendedevent = 12;

    ReportDefinitionChangedEvent reportdefinitionchangedevent = 13;
    PlotSetChangedEvent plotsetchangedevent = 14;
    ResidualPlotChangedEvent residualplotchangedevent = 15;

    ClearSettingsDoneEvent clearsettingsdoneevent = 16;

    AutoPauseEvent autopauseevent = 17;

    CalculationsPausedEvent calculationspausedevent = 18;
    CalculationsResumedEvent calculationsresumedevent = 19;

    /* Fraction of operation completed */
    ProgressEvent progressevent = 20;

    ErrorEvent errorevent = 21;

    CommandCompletedEvent commandcompletedevent = 22;

    DataModelChangedEvent datamodelchangedevent = 23;

    SolverTimeEstimateEvent solvertimeestimateevent = 24;

    ExecuteInClientEvent executeinclientevent = 25;
  }
}
