// Copyright (C) 2021 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
//
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

syntax = "proto3";

package grpcRemoting;

import "ansys/api/fluent/v0/scheme_pointer.proto";

service Events {
  rpc BeginStreaming(BeginStreamingRequest) returns (stream BeginStreamingResponse) {}
}

message TimestepStartedEvent {
  sint64 index = 1;  // Time step index.
  double size = 2;   // Time step size.
}

/**
 * Event at end of the time step.
 */
message TimestepEndedEvent {
  sint64 index = 1;  // Time step index.
  double size = 2;   // Time step size.
}

message IterationStartedEvent {
  sint64 index = 1;  // Iteration index.
}

/**
 * Event at end of the iteration.
 */
message IterationEndedEvent {
  sint64 index = 1;  // Iteration index.
}

/**
 * Event at start of calculation.
 */
message CalculationsStartedEvent {
}

/**
 * Event at end of calculation.
 */
message CalculationsEndedEvent {
}

message CalculationsPausedEvent {
}
message CalculationsResumedEvent {
}

message AboutToReadCaseEvent {
  string casefilepath = 1;  // Case file path.
}

/**
 * Event after case is read.
 */
message CaseReadEvent {
  string casefilepath = 1;  // Case file path.
}

message AboutToReadDataEvent {
  string datafilepath = 1;  // Data file path.
}

/**
 * Event at data read.
 */
message DataReadEvent {
  string datafilepath = 1;  // Data file path.
}

message AboutToInitializeEvent {
}

/**
 * Event at solution initialization.
 */
message InitializedEvent {
}

message ReportDefinitionChangedEvent {
  string reportdefinitionname = 1;
}

message PlotSetChangedEvent {
  string plotsetname = 1;
}

message ResidualPlotChangedEvent {
}

message ClearSettingsDoneEvent {
}

message AutoPauseEvent {
  sint32 level = 1;
  sint64 index = 2;
}

/**
 * Event during solution progress.
 */
message ProgressEvent {
  string message = 1;          // Progress Message.
  sint32 percentComplete = 2;  // Percent completed.
}

message SolverTimeEstimateEvent {
  double hours = 1;
  double minutes = 2;
  double seconds = 3;
}

/*
 * Event when fatal error encountered
 */
message ErrorEvent {
  string message = 1;
  sint32 errorCode = 2;
}

message CommandCompletedEvent {
}

message BeginStreamingRequest {
}

message DataModelChangedEvent {
  repeated string paths = 1;
}

message ExecuteInClientEvent {
  string function = 1;
  repeated SchemePointer arguments = 2;
}

message BeginStreamingResponse {
  oneof as {
    AboutToReadCaseEvent abouttoreadcaseevent = 1;
    CaseReadEvent casereadevent = 2;
    AboutToInitializeEvent abouttoinitializeevent = 3;
    InitializedEvent initializedevent = 4;
    AboutToReadDataEvent abouttoreaddataevent = 5;
    DataReadEvent datareadevent = 6;
    IterationStartedEvent iterationstartedevent = 7;
    IterationEndedEvent iterationendedevent = 8;
    TimestepStartedEvent timestepstartedevent = 9;
    TimestepEndedEvent timestependedevent = 10;
    CalculationsStartedEvent calculationsstartedevent = 11;
    CalculationsEndedEvent calculationsendedevent = 12;
    ReportDefinitionChangedEvent reportdefinitionchangedevent = 13;
    PlotSetChangedEvent plotsetchangedevent = 14;
    ResidualPlotChangedEvent residualplotchangedevent = 15;
    ClearSettingsDoneEvent clearsettingsdoneevent = 16;
    AutoPauseEvent autopauseevent = 17;
    CalculationsPausedEvent calculationspausedevent = 18;
    CalculationsResumedEvent calculationsresumedevent = 19;

    /* Fraction of operation completed */
    ProgressEvent progressevent = 20;
    ErrorEvent errorevent = 21;
    CommandCompletedEvent commandcompletedevent = 22;
    DataModelChangedEvent datamodelchangedevent = 23;
    SolverTimeEstimateEvent solvertimeestimateevent = 24;
    ExecuteInClientEvent executeinclientevent = 25;
  }
}
