//
// Copyright 1987-2023 ANSYS, Inc. All Rights Reserved.
//

syntax = "proto3";

package ansys.api.fluent.v0;

import "ansys/api/fluent/v0/common_api.proto";

service MeshingQueries {
  rpc GetFaceZoneAtLocation(GetFaceZoneAtLocationRequest) returns (GetFaceZoneAtLocationResponse);
  rpc GetCellZoneAtLocation(GetCellZoneAtLocationRequest) returns (GetCellZoneAtLocationResponse);
  rpc GetZonesOfType(GetZonesOfTypeRequest) returns (GetZonesOfTypeResponse);
  rpc GetZonesOfGroup(GetZonesOfGroupRequest) returns (GetZonesOfGroupResponse);
  rpc GetFaceZonesOfFilter(GetFaceZonesOfFilterRequest) returns (GetFaceZonesOfFilterResponse);
  rpc GetCellZonesOfFilter(GetCellZonesOfFilterRequest) returns (GetCellZonesOfFilterResponse);
  rpc GetEdgeZonesOfFilter(GetEdgeZonesOfFilterRequest) returns (GetEdgeZonesOfFilterResponse);
  rpc GetNodeZonesOfFilter(GetNodeZonesOfFilterRequest) returns (GetNodeZonesOfFilterResponse);
  rpc GetObjectsOfType(GetObjectsOfTypeRequest) returns (GetObjectsOfTypeResponse);
  rpc GetFaceZoneIdListOfObject(GetFaceZoneIdListOfObjectRequest) returns (GetFaceZoneIdListOfObjectResponse);
  rpc GetEdgeZoneIdListOfObject(GetEdgeZoneIdListOfObjectRequest) returns (GetEdgeZoneIdListOfObjectResponse);
  rpc GetCellZoneIdListOfObject(GetCellZoneIdListOfObjectRequest) returns (GetCellZoneIdListOfObjectResponse);
  rpc GetFaceZonesSharedByRegionsOfType(GetFaceZonesSharedByRegionsOfTypeRequest) returns (GetFaceZonesSharedByRegionsOfTypeResponse);
  rpc GetFaceZonesOfRegions(GetFaceZonesOfRegionsRequest) returns (GetFaceZonesOfRegionsResponse);
  rpc GetFaceZonesOfLabels(GetFaceZonesOfLabelsRequest) returns (GetFaceZonesOfLabelsResponse);
  rpc GetFaceZoneIdListOfLabels(GetFaceZoneIdListOfLabelsRequest) returns (GetFaceZoneIdListOfLabelsResponse);
  rpc GetFaceZonesOfObjects(GetFaceZonesOfObjectsRequest) returns (GetFaceZonesOfObjectsResponse);
  rpc GetEdgeZonesOfObjects(GetEdgeZonesOfObjectsRequest) returns (GetEdgeZonesOfObjectsResponse);
  rpc GetFaceZoneIdListOfRegions(GetFaceZoneIdListOfRegionsRequest) returns (GetFaceZoneIdListOfRegionsResponse);
  rpc GetPrismCellZones(GetPrismCellZonesRequest) returns (GetPrismCellZonesResponse);
  rpc GetTetCellZones(GetTetCellZonesRequest) returns (GetTetCellZonesResponse);
  rpc GetAdjacentCellZones(GetAdjacentCellZonesRequest) returns (GetAdjacentCellZonesResponse);
  rpc GetAdjacentFaceZones(GetAdjacentFaceZonesRequest) returns (GetAdjacentFaceZonesResponse);
  rpc GetAdjacentInteriorAndBoundaryFaceZones(GetAdjacentInteriorAndBoundaryFaceZonesRequest) returns (GetAdjacentInteriorAndBoundaryFaceZonesResponse);
  rpc GetAdjacentZonesByEdgeConnectivity(GetAdjacentZonesByEdgeConnectivityRequest) returns (GetAdjacentZonesByEdgeConnectivityResponse);
  rpc GetAdjacentZonesByNodeConnectivity(GetAdjacentZonesByNodeConnectivityRequest) returns (GetAdjacentZonesByNodeConnectivityResponse);
}

message GetFaceZoneAtLocationRequest {
  Point location = 1;
}

message GetFaceZoneAtLocationResponse {
  sint64 face_zone_id = 1;
}

message GetCellZoneAtLocationRequest {
  Point location = 1;
}

message GetCellZoneAtLocationResponse {
  sint64 cell_zone_id = 1;
}

message GetZonesOfTypeRequest {
  string input = 1;
}

message GetZonesOfTypeResponse {
  repeated sint64 outputs = 1;
}

message GetZonesOfGroupRequest {
  string input = 1;
}

message GetZonesOfGroupResponse {
  repeated sint64 outputs = 1;
}

message GetFaceZonesOfFilterRequest {
  string input = 1;
}

message GetFaceZonesOfFilterResponse {
  repeated sint64 outputs = 1;
}

message GetCellZonesOfFilterRequest {
  string input = 1;
}

message GetCellZonesOfFilterResponse {
  repeated sint64 outputs = 1;
}

message GetEdgeZonesOfFilterRequest {
  string input = 1;
}

message GetEdgeZonesOfFilterResponse {
  repeated sint64 outputs = 1;
}

message GetNodeZonesOfFilterRequest {
  string input = 1;
}

message GetNodeZonesOfFilterResponse {
  repeated sint64 outputs = 1;
}

message GetObjectsOfTypeRequest {
  string input = 1;
}

message GetObjectsOfTypeResponse {
  repeated string outputs = 1;
}

message GetFaceZoneIdListOfObjectRequest {
  string input = 1;
}

message GetFaceZoneIdListOfObjectResponse {
  repeated sint64 outputs = 1;
}

message GetEdgeZoneIdListOfObjectRequest {
  string input = 1;
}

message GetEdgeZoneIdListOfObjectResponse {
  repeated sint64 outputs = 1;
}

message GetCellZoneIdListOfObjectRequest {
  string input = 1;
}

message GetCellZoneIdListOfObjectResponse {
  repeated sint64 outputs = 1;
}

message GetFaceZonesSharedByRegionsOfTypeRequest {
  string input_1 = 1;
  string input_2 = 2;
}

message GetFaceZonesSharedByRegionsOfTypeResponse {
  repeated sint64 outputs = 1;
}

message GetFaceZonesOfRegionsRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetFaceZonesOfRegionsResponse {
  repeated sint64 outputs = 1;
}

message GetFaceZonesOfLabelsRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetFaceZonesOfLabelsResponse {
  repeated sint64 outputs = 1;
}

message GetFaceZoneIdListOfLabelsRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetFaceZoneIdListOfLabelsResponse {
  repeated sint64 outputs = 1;
}

message GetFaceZonesOfObjectsRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetFaceZonesOfObjectsResponse {
  repeated sint64 outputs = 1;
}

message GetEdgeZonesOfObjectsRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetEdgeZonesOfObjectsResponse {
  repeated sint64 outputs = 1;
}

message GetFaceZoneIdListOfRegionsRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetFaceZoneIdListOfRegionsResponse {
  repeated sint64 outputs = 1;
}

message GetPrismCellZonesRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetPrismCellZonesResponse {
  repeated sint64 outputs = 1;
}

message GetTetCellZonesRequest {
  string input = 1;
  repeated string inputs = 2;
}

message GetTetCellZonesResponse {
  repeated sint64 outputs = 1;
}

message GetAdjacentCellZonesRequest {
  string input = 1;
  repeated sint64 inputs = 2;
}

message GetAdjacentCellZonesResponse {
  repeated sint64 outputs = 1;
}

message GetAdjacentFaceZonesRequest {
  string input = 1;
  repeated sint64 inputs = 2;
}

message GetAdjacentFaceZonesResponse {
  repeated sint64 outputs = 1;
}

message GetAdjacentInteriorAndBoundaryFaceZonesRequest {
  string input = 1;
  repeated sint64 inputs = 2;
}

message GetAdjacentInteriorAndBoundaryFaceZonesResponse {
  repeated sint64 outputs = 1;
}

message GetAdjacentZonesByEdgeConnectivityRequest {
  string input = 1;
  repeated sint64 inputs = 2;
}

message GetAdjacentZonesByEdgeConnectivityResponse {
  repeated sint64 outputs = 1;
}

message GetAdjacentZonesByNodeConnectivityRequest {
  string input = 1;
  repeated sint64 inputs = 2;
}

message GetAdjacentZonesByNodeConnectivityResponse {
  repeated sint64 outputs = 1;
}
