//
// Copyright 1987-2023 ANSYS, Inc. All Rights Reserved.
//

syntax = "proto3";

package ansys.api.fluent.v0;

import "ansys/api/fluent/v0/common_api.proto";

import "ansys/api/fluent/v0/variant.proto";

service Reduction {
  rpc Area(AreaRequest) returns (AreaResponse) {}
  rpc AreaAve(AreaAveRequest) returns (AreaAveResponse) {}
  rpc AreaInt(AreaIntRequest) returns (AreaIntResponse) {}
  rpc Centroid(CentroidRequest) returns (CentroidResponse) {}
  rpc Count(CountRequest) returns (CountResponse) {}
  rpc CountIf(CountIfRequest) returns (CountIfResponse) {}
  rpc Force(ForceRequest) returns (ForceResponse) {}
  rpc MassAve(MassAveRequest) returns (MassAveResponse) {}
  rpc MassFlowAve(MassFlowAveRequest) returns (MassFlowAveResponse) {}
  rpc MassFlowAveAbs(MassFlowAveAbsRequest) returns (MassFlowAveAbsResponse) {}
  rpc MassFlowInt(MassFlowIntRequest) returns (MassFlowIntResponse) {}
  rpc MassInt(MassIntRequest) returns (MassIntResponse) {}
  rpc Maximum(MaximumRequest) returns (MaximumResponse) {}
  rpc Minimum(MinimumRequest) returns (MinimumResponse) {}
  rpc PressureForce(PressureForceRequest) returns (PressureForceResponse) {}
  rpc ViscousForce(ViscousForceRequest) returns (ViscousForceResponse) {}
  rpc Volume(VolumeRequest) returns (VolumeResponse) {}
  rpc VolumeAve(VolumeAveRequest) returns (VolumeAveResponse) {}
  rpc VolumeInt(VolumeIntRequest) returns (VolumeIntResponse) {}
  rpc Moment(MomentRequest) returns (MomentResponse) {}
  rpc Sum(SumRequest) returns (SumResponse) {}
  rpc SumIf(SumIfRequest) returns (SumIfResponse) {}
}

message AreaRequest {
  repeated string locations = 1;
}

message AreaResponse {
  utils.Variant value = 1;
}

message AreaAveRequest {
  string expression = 1;
  repeated string locations = 2;
}

message AreaAveResponse {
  utils.Variant value = 1;
}

message AreaIntRequest {
  string expression = 1;
  repeated string locations = 2;
}

message AreaIntResponse {
  utils.Variant value = 1;
}

message CentroidRequest {
  repeated string locations = 1;
}

message CentroidResponse {
  Point value = 1;
}

message CountRequest {
  repeated string locations = 1;
}

message CountResponse {
  utils.Variant value = 1;
}

message CountIfRequest {
  string condition = 1;
  repeated string locations = 2;
}

message CountIfResponse {
  utils.Variant value = 1;
}

message ForceRequest {
  repeated string locations = 1;
}

message ForceResponse {
  Point value = 1;
}

message MassAveRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MassAveResponse {
  utils.Variant value = 1;
}

message MassFlowAveRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MassFlowAveResponse {
  utils.Variant value = 1;
}

message MassFlowAveAbsRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MassFlowAveAbsResponse {
  utils.Variant value = 1;
}

message MassFlowIntRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MassFlowIntResponse {
  utils.Variant value = 1;
}

message MassIntRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MassIntResponse {
  utils.Variant value = 1;
}

message MaximumRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MaximumResponse {
  utils.Variant value = 1;
}

message MinimumRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MinimumResponse {
  utils.Variant value = 1;
}

message PressureForceRequest {
  repeated string locations = 1;
}

message PressureForceResponse {
  Point value = 1;
}

message ViscousForceRequest {
  repeated string locations = 1;
}

message ViscousForceResponse {
  Point value = 1;
}

message VolumeRequest {
  repeated string locations = 1;
}

message VolumeResponse {
  utils.Variant value = 1;
}

message VolumeAveRequest {
  string expression = 1;
  repeated string locations = 2;
}

message VolumeAveResponse {
  utils.Variant value = 1;
}

message VolumeIntRequest {
  string expression = 1;
  repeated string locations = 2;
}

message VolumeIntResponse {
  utils.Variant value = 1;
}

message MomentRequest {
  string expression = 1;
  repeated string locations = 2;
}

message MomentResponse {
  Point value = 1;
}

message SumRequest {
  string expression = 1;
  repeated string locations = 2;
  string weight = 3;
}

message SumResponse {
  utils.Variant value = 1;
}

message SumIfRequest {
  string expression = 1;
  string condition = 2;
  repeated string locations = 3;
  string weight = 4;
}

message SumIfResponse {
  utils.Variant value = 1;
}
