// Copyright (C) 2021 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package grpcRemoting;

import "ansys/api/fluent/v0/scheme_pointer.proto";

service SchemeEval {
  rpc Eval(SchemePointer) returns (SchemePointer) {
    option deprecated = true;
  }
  rpc SchemeEval(SchemeEvalRequest) returns (SchemeEvalResponse);
  rpc Exec(ExecRequest) returns (ExecResponse);
  rpc StringEval(StringEvalRequest) returns (StringEvalResponse);
}

message ExecRequest {
  repeated string command = 1;
  bool wait = 2;
  bool silent = 3;  // if true, input won't be printed
}

message ExecResponse {
  string output = 1;
}

message SchemeEvalRequest {
  SchemePointer input = 1;
}

message SchemeEvalResponse {
  SchemePointer output = 1;
}

message StringEvalRequest {
  string input = 1;
}

message StringEvalResponse {
  string output = 1;
}
