// Copyright (C) 2021 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package grpcRemoting;

import "ansys/api/fluent/v0/common.proto";

message SchemePointer {
  message SchemePair {
    SchemePointer car = 1;
    SchemePointer cdr = 2;
  }

  message SchemeList {
    repeated SchemePointer item = 1;
  }

  oneof val {
    Empty empty = 1;
    string sym = 2;
    SchemePair pair = 3;
    SchemeList list = 9;
    double flonum = 4;
    sint64 fixednum = 5;
    string c = 6;
    string str = 7;
    bool b = 8;
  }
}
