//
// Copyright 2026 ANSYS, Inc. Unauthorized use, distribution, or duplication is prohibited.
//

syntax = "proto3";

package ansys.api.fluent.v1.solution_variable;

import "ansys/api/fluent/v1/field_data.proto";

// SolutionVariable service provides RPCs for retrieving and setting solution variable data and metadata.
service SolutionVariable {
  // Retrieve domain and zone metadata.
  rpc GetZonesInfo(GetZonesInfoRequest) returns (GetZonesInfoResponse);
  // Retrieve solution variable metadata for a domain and zone.
  rpc GetSolutionVariableInfo(GetSolutionVariableInfoRequest) returns (GetSolutionVariableInfoResponse);
  // Retrieve solution variable data, streamed in chunks.
  rpc GetSolutionVariableData(GetSolutionVariableDataRequest) returns (stream GetSolutionVariableDataResponse);
  // Set solution variable data by streaming data chunks to the server.
  rpc SetSolutionVariableData(stream SetSolutionVariableDataRequest) returns (SetSolutionVariableDataResponse);
}

// Request to retrieve domain and zone metadata.
message GetZonesInfoRequest {
}

// Response containing domain and zone metadata.
message GetZonesInfoResponse {
  repeated DomainInfo domains_info = 1;  // Domains info.
  repeated ZoneInfo zones_info = 2;      // Zones info.
}

// Domain metadata.
message DomainInfo {
  string name = 1;       // Domain name.
  uint32 domain_id = 2;  // Domain ID.
}

// Zone metadata.
message ZoneInfo {
  string name = 1;                             // Zone name.
  uint64 zone_id = 2;                          // Zone ID.
  string zone_type = 3;                        // Zone type, e.g., velocity-inlet.
  ThreadType thread_type = 4;                  // Zone thread type.
  repeated PartitionInfo partitions_info = 5;  // Partitions info.
}

// Thread type of the zone.
enum ThreadType {
  // Default value. Thread type is unspecified.
  THREAD_TYPE_UNSPECIFIED = 0;
  // Zone uses cell threads.
  THREAD_TYPE_CELL = 1;
  // Zone uses face threads.
  THREAD_TYPE_FACE = 2;
}

// Partition range metadata.
message PartitionInfo {
  uint64 count = 1;        // Count in partition
  uint64 start_index = 2;  // Global start index
  uint64 end_index = 3;    // Global end index
}

// Request to retrieve solution metadata for a given domain and zone.
message GetSolutionVariableInfoRequest {
  uint32 domain_id = 1;  // Domain ID.
  uint64 zone_id = 2;    // Zone ID.
}

// Response containing solution metadata.
message GetSolutionVariableInfoResponse {
  repeated SolutionVariableInfo svars_info = 1;  // Solution variable info.
}

// Solution variable information.
message SolutionVariableInfo {
  string name = 1;                                          // Solution variable name.
  uint32 dimension = 2;                                     // Dimension e.g. for centroid it will be 3.
  ansys.api.fluent.v1.field_data.FieldType field_type = 3;  // Data type defined in field_data.proto.
}

// Request to retrieve solution variable data, possibly streamed in chunks.
message GetSolutionVariableDataRequest {
  uint32 chunk_size = 1;          // Chunk size.
  bool provide_bytes_stream = 2;  // Bytes are streamed if true.
  string name = 3;                // Solution variable Name.
  uint32 domain_id = 4;           // Domain ID.
  repeated uint64 zones = 5;      // List of zone IDs.
}

// Streamed response containing payload or payload info.
message GetSolutionVariableDataResponse {
  oneof array {
    Payload payload = 1;    // Payload.
    Info payload_info = 2;  // Payload info.
  }
}

// Payload metadata.
message Info {
  ansys.api.fluent.v1.field_data.FieldType field_type = 1;  // Field type.
  uint64 field_size = 2;                                    // Field size. For bytes it will be number of bytes otherwise array size.
  uint64 zone = 3;                                          // Zone ID.
}

// Payload chunk union.
message Payload {
  oneof chunk {
    bytes byte_payload = 1;                                           // Bytes payload.
    ansys.api.fluent.v1.field_data.DoublePayload double_payload = 2;  // Double payload.
    ansys.api.fluent.v1.field_data.FloatPayload float_payload = 3;    // Float payload.
    ansys.api.fluent.v1.field_data.LongPayload long_payload = 4;      // Long payload.
    ansys.api.fluent.v1.field_data.IntPayload int_payload = 5;        // Int payload.
  }
}

// Request to set solution variable data via a streaming API.
message SetSolutionVariableDataRequest {
  oneof array {
    SolutionVariableHeader header = 1;  // Solution variable name and domain ID.
    Payload payload = 2;                // Payload.
    Info payload_info = 3;              // Payload info.
  }
}

// Solution variable header containing the name and domain ID.
message SolutionVariableHeader {
  string name = 1;       // Solution variable Name.
  uint32 domain_id = 2;  // Domain ID.
}

// Response to the SetSolutionVariableData request.
message SetSolutionVariableDataResponse {
}
