repos:

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.1
  hooks:
    - id: clang-format
      files: ^.+.proto$
      args: [ -i, -style=file ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/yoheimuta/protolint
  rev: v0.44.0
  hooks:
  - id: protolint

- repo: https://github.com/bufbuild/buf
  rev: v1.28.1
  hooks:
  - id: buf-lint
    name: Buf Lint V1 Protos
    entry: buf lint --path ansys/api/fluent/v1
    language: system
    files: ^ansys/api/fluent/v1/.*\.proto$
    pass_filenames: false

#  - id: buf-format
#    name: Buf Format V1 Protos
#    entry: buf format -w --path ansys/api/fluent/v1
#    language: system
#    files: ^ansys/api/fluent/v1/.*\.proto$
#    pass_filenames: false
