repos:

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.1
  hooks:
  - id: clang-format
    files: ^.+.proto$
    args: [ -i, -style=file ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: [--ignore-words-list, "Synopsys,synopsys"]

- repo: https://github.com/yoheimuta/protolint
  rev: v0.56.3
  hooks:
  - id: protolint
    files: ^ansys/api/fluent/v1/.*\.proto$

- repo: https://github.com/ansys/pre-commit-hooks
  rev: 55c5b6a5439abd847613579c6924da750e8b78b2 # frozen: v0.8.0
  hooks:
    - id: add-license-headers
      args:
      - --start_year=2021
      - --custom_license=Apache-2.0
