# Lint directives.
# Documentation:
# https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml

lint:
  rules:
    # Enable all default rules (Google protobuf style)
    all_default: true

    # Disable rules that flag prepositions in message names (e.g. "PauseSolveForRequest").
    remove:
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS

  # Linter rules option.
  rules_option:
    max_line_length:
      max_chars: 160

