"""Sphinx extension that generates API reference fragments from .proto files.

For each ``.proto`` file under ``ansys/api/fluent/v1`` this extension produces
an RST fragment under ``docs/source/api/_generated/<basename>.rst`` containing:

* a metadata block (source file, proto package, content counts),
* the list of RPCs defined by services in that file (with leading comments),
* every message with a table of its fields (name, tag, type, comment),
* every enum with a table of its values.

Comments are extracted from the proto ``SourceCodeInfo`` produced by
``grpc_tools.protoc``. Hand-curated narrative pages in ``api/services``,
``api/helpers`` and ``api/legacy`` consume these fragments via an
``.. include::`` directive at the bottom of each page.

The matching stylesheet at ``docs/source/_static/proto_docgen.css`` controls
the visual layout of the generated blocks.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable

from google.protobuf import descriptor_pb2

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent
_PROTO_ROOT = _REPO_ROOT / "ansys" / "api" / "fluent" / "v1"
_API_DIR = _REPO_ROOT / "docs" / "source" / "api"
_OUT_DIR = _API_DIR / "_generated"

# Indentation used inside ``.. container::`` directive bodies.
_INDENT = "   "

# ---------------------------------------------------------------------------
# Section layout for the API reference
# ---------------------------------------------------------------------------
#
# The proto files belonging to each top-level API reference section, together
# with the human-readable title shown for each generated page. Order is
# preserved in the section index toctree.
#
# Adding a new proto:
# - Drop it into ``ansys/api/fluent/v1``.
# - Append ``("<stem>", "<Display title>")`` to the right group below.
#
# The extension generates one ``.rst`` per entry plus an ``index.rst`` with a
# toctree. Files in these directories are fully owned by the extension and
# rewritten on every build.
_API_SECTIONS: tuple[tuple[str, str, str, tuple[tuple[str, str], ...]], ...] = (
    (
        "services",
        "Services",
        (
            "Auto-generated proto reference for every gRPC service in\n"
            "``ansys.api.fluent.v1``. Each page lists the service's RPCs together\n"
            "with the messages and enums declared in the same proto file.\n"
        ),
        (
            ("health", "Health"),
            ("app_utilities", "ApplicationRuntime"),
            ("datamodel_se", "DataModel"),
            ("settings", "Settings"),
            ("events", "Events"),
            ("field_data", "FieldData"),
            ("monitor", "Monitor"),
            ("reduction", "Reduction"),
            ("svar", "SolutionVariable"),
            ("transcript", "Transcript"),
            ("connection", "Connection"),
        ),
    ),
    (
        "helpers",
        "Helper modules",
        (
            "Auto-generated proto reference for shared message types used across\n"
            "multiple Fluent services. These are support modules, not standalone\n"
            "gRPC services.\n"
        ),
        (
            ("primitives", "Primitives"),
            ("scheme_pointer", "SchemePointer"),
            ("variant", "Variant"),
        ),
    ),
    (
        "legacy",
        "Legacy",
        (
            "Auto-generated proto reference for older services retained for\n"
            "backward compatibility. Prefer current service equivalents for new\n"
            "work.\n"
        ),
        (
            ("datamodel_tui", "TextInterface"),
            ("scheme_eval", "SchemeInterpreter"),
        ),
    ),
)

# Marker placed at the top of every auto-generated page so we know it is safe
# to overwrite or delete on the next build.
_AUTO_HEADER = (
    ".. Auto-generated by docs/_ext/proto_docgen.py — do not edit by hand.\n"
    ".. Edit the proto files or the section layout in proto_docgen.py instead.\n"
)


# ---------------------------------------------------------------------------
# FileDescriptorSet construction
# ---------------------------------------------------------------------------


def _compile_descriptor_set(proto_files: Iterable[Path]) -> descriptor_pb2.FileDescriptorSet:
    """Run ``protoc`` to compile *proto_files* into a ``FileDescriptorSet``.

    ``--include_source_info`` is required so that field/RPC comments survive
    into the descriptor.
    """
    with tempfile.TemporaryDirectory() as tmp:
        out_path = Path(tmp) / "descriptors.pb"
        cmd = [
            sys.executable,
            "-m",
            "grpc_tools.protoc",
            f"--proto_path={_REPO_ROOT.as_posix()}",
            f"--descriptor_set_out={out_path}",
            "--include_source_info",
            "--include_imports",
        ]
        cmd.extend(p.relative_to(_REPO_ROOT).as_posix() for p in proto_files)
        subprocess.run(cmd, check=True, cwd=_REPO_ROOT)
        fds = descriptor_pb2.FileDescriptorSet()
        fds.ParseFromString(out_path.read_bytes())
        return fds


# ---------------------------------------------------------------------------
# Comment extraction
# ---------------------------------------------------------------------------


def _build_comment_index(file_proto: descriptor_pb2.FileDescriptorProto) -> dict[tuple[int, ...], str]:
    """Index leading + trailing comments by ``SourceCodeInfo.Location.path``."""
    index: dict[tuple[int, ...], str] = {}
    for loc in file_proto.source_code_info.location:
        text = (loc.leading_comments or "") + (loc.trailing_comments or "")
        text = text.strip()
        if text:
            index[tuple(loc.path)] = text
    return index


def _clean_comment(text: str) -> str:
    """Normalize comment text into a single-paragraph RST-safe string."""
    if not text:
        return ""
    lines = [ln.strip().lstrip("*").strip() for ln in text.splitlines()]
    lines = [ln for ln in lines if ln]
    return " ".join(lines)


# ---------------------------------------------------------------------------
# Type rendering
# ---------------------------------------------------------------------------


_FIELD_TYPE_NAMES = {
    descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE: "double",
    descriptor_pb2.FieldDescriptorProto.TYPE_FLOAT: "float",
    descriptor_pb2.FieldDescriptorProto.TYPE_INT64: "int64",
    descriptor_pb2.FieldDescriptorProto.TYPE_UINT64: "uint64",
    descriptor_pb2.FieldDescriptorProto.TYPE_INT32: "int32",
    descriptor_pb2.FieldDescriptorProto.TYPE_FIXED64: "fixed64",
    descriptor_pb2.FieldDescriptorProto.TYPE_FIXED32: "fixed32",
    descriptor_pb2.FieldDescriptorProto.TYPE_BOOL: "bool",
    descriptor_pb2.FieldDescriptorProto.TYPE_STRING: "string",
    descriptor_pb2.FieldDescriptorProto.TYPE_BYTES: "bytes",
    descriptor_pb2.FieldDescriptorProto.TYPE_UINT32: "uint32",
    descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED32: "sfixed32",
    descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED64: "sfixed64",
    descriptor_pb2.FieldDescriptorProto.TYPE_SINT32: "sint32",
    descriptor_pb2.FieldDescriptorProto.TYPE_SINT64: "sint64",
}


def _short_type_name(type_name: str) -> str:
    """Strip the proto package prefix from a fully-qualified type name."""
    return type_name.lstrip(".").rsplit(".", 1)[-1]


def _anchor_for(file_stem: str, qualified_name: str) -> str:
    return f"proto-{file_stem}-{qualified_name.lower().replace('.', '-')}"


def _build_type_index(
    file_protos: Iterable[descriptor_pb2.FileDescriptorProto],
) -> dict[str, tuple[str, str]]:
    """Map fully-qualified proto type names to ``(file_stem, qualified_name)``.

    The qualified name is the dotted path within the file (e.g.
    ``Outer.Inner``) used to build anchors.
    """
    index: dict[str, tuple[str, str]] = {}

    def _walk_message(
        msg: descriptor_pb2.DescriptorProto,
        package: str,
        file_stem: str,
        qualified: str,
    ) -> None:
        full = f".{package}.{qualified}" if package else f".{qualified}"
        index[full] = (file_stem, qualified)
        for nested in msg.nested_type:
            if nested.options.map_entry:
                continue
            _walk_message(
                nested, package, file_stem, f"{qualified}.{nested.name}"
            )
        for enum in msg.enum_type:
            enum_q = f"{qualified}.{enum.name}"
            full_e = f".{package}.{enum_q}" if package else f".{enum_q}"
            index[full_e] = (file_stem, enum_q)

    for fp in file_protos:
        file_stem = Path(fp.name).stem
        package = fp.package
        for msg in fp.message_type:
            _walk_message(msg, package, file_stem, msg.name)
        for enum in fp.enum_type:
            full_e = f".{package}.{enum.name}" if package else f".{enum.name}"
            index[full_e] = (file_stem, enum.name)
    return index


def _render_type_ref(
    full_type_name: str, type_index: dict[str, tuple[str, str]]
) -> str:
    """Render a message/enum type as a clickable ``:ref:`` link if known."""
    short = _short_type_name(full_type_name)
    target = type_index.get(full_type_name)
    if target is None:
        return f"``{short}``"
    file_stem, qualified = target
    anchor = _anchor_for(file_stem, qualified)
    # ``:ref:`` cannot contain nested inline literals, so the link text is
    # rendered as plain text. The CSS gives proto blocks enough emphasis
    # that monospace on the type cell is not strictly necessary.
    return f":ref:`{short} <{anchor}>`"


def _render_field_type(
    field: descriptor_pb2.FieldDescriptorProto,
    type_index: dict[str, tuple[str, str]],
) -> str:
    if field.type in (
        descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE,
        descriptor_pb2.FieldDescriptorProto.TYPE_ENUM,
    ):
        return _render_type_ref(field.type_name, type_index)
    return f"``{_FIELD_TYPE_NAMES.get(field.type, str(field.type))}``"


# ---------------------------------------------------------------------------
# RST emission helpers
# ---------------------------------------------------------------------------


def _heading(title: str, char: str) -> str:
    return f"{title}\n{char * len(title)}\n"


def _rst_escape_cell(text: str) -> str:
    """Escape characters that would break a list-table cell."""
    if not text:
        return ""
    return text.replace("|", r"\|")


def _qualifier_badges(field: descriptor_pb2.FieldDescriptorProto, oneof_name: str | None) -> str:
    """Return inline ``:guilabel:`` badges describing a field's qualifiers."""
    badges: list[str] = []
    if field.label == descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED:
        badges.append(":guilabel:`repeated`")
    if oneof_name is not None:
        badges.append(f":guilabel:`oneof: {oneof_name}`")
    return " ".join(badges)


def _emit_list_table_header(out: list[str], indent: str, headers: list[tuple[str, int]]) -> None:
    widths = " ".join(str(w) for _, w in headers)
    out.append(f"{indent}.. list-table::")
    out.append(f"{indent}   :widths: {widths}")
    out.append(f"{indent}   :header-rows: 1")
    out.append(f"{indent}   :class: proto-table")
    out.append("")
    for i, (title, _) in enumerate(headers):
        marker = "* - " if i == 0 else "  - "
        out.append(f"{indent}   {marker}{title}")


def _emit_list_table_row(out: list[str], indent: str, cells: list[str]) -> None:
    for i, cell in enumerate(cells):
        marker = "* - " if i == 0 else "  - "
        out.append(f"{indent}   {marker}{cell}")


# ---------------------------------------------------------------------------
# Section emitters
# ---------------------------------------------------------------------------


def _emit_service(
    out: list[str],
    service: descriptor_pb2.ServiceDescriptorProto,
    service_idx: int,
    comments: dict[tuple[int, ...], str],
    file_stem: str,
    type_index: dict[str, tuple[str, str]],
) -> None:
    out.append(f".. _proto-{file_stem}-service-{service.name.lower()}:")
    out.append("")
    out.append(".. container:: proto-block proto-service")
    out.append("")
    out.append(f"{_INDENT}.. rubric:: Service ``{service.name}``")
    out.append("")

    svc_doc = _clean_comment(comments.get((6, service_idx), ""))
    if svc_doc:
        out.append(f"{_INDENT}.. container:: proto-doc")
        out.append("")
        out.append(f"{_INDENT}{_INDENT}{svc_doc}")
        out.append("")

    if not service.method:
        return

    _emit_list_table_header(
        out,
        _INDENT,
        [("RPC", 22), ("Request", 26), ("Response", 26), ("Description", 36)],
    )
    for method_idx, method in enumerate(service.method):
        method_doc = _clean_comment(comments.get((6, service_idx, 2, method_idx), ""))
        request_ref = _render_type_ref(method.input_type, type_index)
        response_ref = _render_type_ref(method.output_type, type_index)
        request_cell = (
            f":guilabel:`stream` {request_ref}" if method.client_streaming else request_ref
        )
        response_cell = (
            f":guilabel:`stream` {response_ref}" if method.server_streaming else response_ref
        )
        _emit_list_table_row(
            out,
            _INDENT,
            [
                f"``{method.name}``",
                request_cell,
                response_cell,
                _rst_escape_cell(method_doc) or "—",
            ],
        )
    out.append("")


def _emit_message(
    out: list[str],
    msg: descriptor_pb2.DescriptorProto,
    comments: dict[tuple[int, ...], str],
    path_prefix: tuple[int, ...],
    qualified_name: str,
    file_stem: str,
    type_index: dict[str, tuple[str, str]],
) -> None:
    anchor = _anchor_for(file_stem, qualified_name)
    out.append(f".. _{anchor}:")
    out.append("")
    out.append(".. container:: proto-block proto-message")
    out.append("")
    out.append(f"{_INDENT}.. rubric:: ``{qualified_name}``")
    out.append("")

    msg_doc = _clean_comment(comments.get(path_prefix, ""))
    if msg_doc:
        out.append(f"{_INDENT}.. container:: proto-doc")
        out.append("")
        out.append(f"{_INDENT}{_INDENT}{msg_doc}")
        out.append("")

    if msg.field:
        oneof_names = {i: oneof.name for i, oneof in enumerate(msg.oneof_decl)}
        _emit_list_table_header(
            out,
            _INDENT,
            [("Field", 22), ("#", 6), ("Type", 22), ("Description", 50)],
        )
        for field_idx, field in enumerate(msg.field):
            field_doc = _clean_comment(comments.get(path_prefix + (2, field_idx), ""))
            oneof_name = (
                oneof_names.get(field.oneof_index)
                if field.HasField("oneof_index")
                else None
            )
            qualifiers = _qualifier_badges(field, oneof_name)
            type_repr = _render_field_type(field, type_index)
            type_cell = f"{qualifiers} {type_repr}" if qualifiers else type_repr
            _emit_list_table_row(
                out,
                _INDENT,
                [
                    f"``{field.name}``",
                    str(field.number),
                    type_cell,
                    _rst_escape_cell(field_doc) or "—",
                ],
            )
        out.append("")

    # Nested enums
    for enum_idx, enum in enumerate(msg.enum_type):
        _emit_enum(
            out,
            enum,
            comments,
            path_prefix + (4, enum_idx),
            f"{qualified_name}.{enum.name}",
            file_stem,
        )

    # Nested messages (skip synthetic map entries)
    for nested_idx, nested in enumerate(msg.nested_type):
        if nested.options.map_entry:
            continue
        _emit_message(
            out,
            nested,
            comments,
            path_prefix + (3, nested_idx),
            f"{qualified_name}.{nested.name}",
            file_stem,
            type_index,
        )


def _emit_enum(
    out: list[str],
    enum: descriptor_pb2.EnumDescriptorProto,
    comments: dict[tuple[int, ...], str],
    path_prefix: tuple[int, ...],
    qualified_name: str,
    file_stem: str,
) -> None:
    anchor = _anchor_for(file_stem, qualified_name)
    out.append(f".. _{anchor}:")
    out.append("")
    out.append(".. container:: proto-block proto-enum")
    out.append("")
    out.append(f"{_INDENT}.. rubric:: ``{qualified_name}`` (enum)")
    out.append("")

    enum_doc = _clean_comment(comments.get(path_prefix, ""))
    if enum_doc:
        out.append(f"{_INDENT}.. container:: proto-doc")
        out.append("")
        out.append(f"{_INDENT}{_INDENT}{enum_doc}")
        out.append("")

    _emit_list_table_header(
        out,
        _INDENT,
        [("Name", 32), ("#", 6), ("Description", 60)],
    )
    for value_idx, value in enumerate(enum.value):
        value_doc = _clean_comment(comments.get(path_prefix + (2, value_idx), ""))
        _emit_list_table_row(
            out,
            _INDENT,
            [
                f"``{value.name}``",
                str(value.number),
                _rst_escape_cell(value_doc) or "—",
            ],
        )
    out.append("")


def _emit_group_heading(out: list[str], title: str) -> None:
    out.append(".. rst-class:: proto-group-heading")
    out.append("")
    out.append(title)
    out.append("")


def _emit_metadata_block(out: list[str], file_proto: descriptor_pb2.FileDescriptorProto) -> None:
    """Emit a styled metadata header (source file + proto package) on
    separate lines using an RST field list inside a styled container.
    """
    proto_path = f"ansys/api/fluent/v1/{Path(file_proto.name).name}"
    out.append(".. container:: proto-meta")
    out.append("")
    out.append(f"{_INDENT}:Source file: :file:`{proto_path}`")
    out.append(f"{_INDENT}:Proto package: ``{file_proto.package}``")

    counts: list[str] = []
    if file_proto.service:
        n = len(file_proto.service)
        counts.append(f"{n} service" + ("s" if n != 1 else ""))
    if file_proto.message_type:
        n = len(file_proto.message_type)
        counts.append(f"{n} message" + ("s" if n != 1 else ""))
    if file_proto.enum_type:
        n = len(file_proto.enum_type)
        counts.append(f"{n} enum" + ("s" if n != 1 else ""))
    if counts:
        out.append(f"{_INDENT}:Contains: {', '.join(counts)}")
    out.append("")


def _emit_file(
    file_proto: descriptor_pb2.FileDescriptorProto,
    type_index: dict[str, tuple[str, str]],
) -> str:
    comments = _build_comment_index(file_proto)
    file_stem = Path(file_proto.name).stem
    out: list[str] = []
    out.append(".. Auto-generated by docs/_ext/proto_docgen.py — do not edit by hand.")
    out.append("")
    # Use a ``rubric`` rather than a section heading so the fragment can be
    # included directly under any parent section without affecting the
    # heading-level hierarchy of the including page. All deeper subdivisions
    # inside the fragment use ``.. rubric::`` directives or ``.. container::``
    # blocks, which behave like headings visually but do not participate in
    # the section hierarchy. This keeps the fragment compatible with any
    # parent page heading convention and lets multiple fragments be embedded
    # back-to-back in a single page (e.g. the API reference index pages).
    out.append(".. rubric:: Generated reference")
    out.append("   :class: proto-generated-reference")
    out.append("")

    _emit_metadata_block(out, file_proto)

    if file_proto.service:
        _emit_group_heading(out, "Services")
        for service_idx, service in enumerate(file_proto.service):
            _emit_service(
                out, service, service_idx, comments, file_stem, type_index
            )

    if file_proto.message_type:
        _emit_group_heading(out, "Messages")
        for msg_idx, msg in enumerate(file_proto.message_type):
            _emit_message(
                out, msg, comments, (4, msg_idx), msg.name, file_stem, type_index
            )

    if file_proto.enum_type:
        _emit_group_heading(out, "Enumerations")
        for enum_idx, enum in enumerate(file_proto.enum_type):
            _emit_enum(out, enum, comments, (5, enum_idx), enum.name, file_stem)

    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Sphinx hook
# ---------------------------------------------------------------------------


def generate(app=None) -> None:
    """Compile v1 protos and write generated RST fragments to disk."""
    proto_files = sorted(_PROTO_ROOT.glob("*.proto"))
    if not proto_files:
        return

    if _OUT_DIR.exists():
        shutil.rmtree(_OUT_DIR)
    _OUT_DIR.mkdir(parents=True, exist_ok=True)

    fds = _compile_descriptor_set(proto_files)
    requested = {p.name for p in proto_files}
    emitted_files = [
        fp for fp in fds.file if Path(fp.name).name in requested
    ]
    type_index = _build_type_index(emitted_files)
    written: list[str] = []
    for file_proto in emitted_files:
        rst = _emit_file(file_proto, type_index)
        out_path = _OUT_DIR / f"{Path(file_proto.name).stem}.rst"
        out_path.write_text(rst, encoding="utf-8")
        written.append(out_path.name)

    # Stub index so Sphinx does not warn about an empty directory.
    (_OUT_DIR / "README.rst").write_text(
        ":orphan:\n\nAuto-generated proto reference fragments. Included from hand-written pages.\n",
        encoding="utf-8",
    )

    _write_section_pages()

    if app is not None:
        try:
            from sphinx.util import logging as sphinx_logging

            sphinx_logging.getLogger(__name__).info(
                "proto_docgen: regenerated %d RST fragment(s)", len(written)
            )
        except Exception:
            pass


def _write_section_pages() -> None:
    """Write per-section index pages and one ``.rst`` per proto stem.

    Files in the section directories (``api/services``, ``api/helpers``,
    ``api/legacy``) are owned entirely by this extension. Any pre-existing
    auto-generated ``.rst`` is removed so that renames in ``_API_SECTIONS``
    do not leave stale pages behind. Hand-written files are never touched
    because we only delete files starting with the ``_AUTO_HEADER`` marker.
    """
    for dir_name, section_title, intro, members in _API_SECTIONS:
        section_dir = _API_DIR / dir_name
        section_dir.mkdir(parents=True, exist_ok=True)

        # Remove previously auto-generated rst files (so renames don't leave
        # orphans). Leave hand-edited files alone.
        for existing in section_dir.glob("*.rst"):
            try:
                head = existing.read_text(encoding="utf-8")[: len(_AUTO_HEADER)]
            except OSError:
                continue
            if head.startswith(_AUTO_HEADER[:60]):
                existing.unlink()

        # Per-member pages.
        for stem, title in members:
            bar = "=" * len(title)
            page = (
                f"{_AUTO_HEADER}\n"
                f"{title}\n{bar}\n\n"
                f".. include:: ../_generated/{stem}.rst\n"
            )
            (section_dir / f"{stem}.rst").write_text(page, encoding="utf-8")

        # Section index page with a toctree of the member pages.
        bar = "=" * len(section_title)
        lines: list[str] = [_AUTO_HEADER, ""]
        lines.append(bar)
        lines.append(section_title)
        lines.append(bar)
        lines.append("")
        lines.append(intro.rstrip())
        lines.append("")
        lines.append(".. list-table::")
        lines.append("   :widths: 30 70")
        lines.append("   :header-rows: 1")
        lines.append("")
        lines.append("   * - Page")
        lines.append("     - Proto file")
        for stem, title in members:
            lines.append(f"   * - :doc:`{title} <{stem}>`")
            lines.append(f"     - ``{stem}.proto``")
        lines.append("")
        lines.append(".. toctree::")
        lines.append("   :hidden:")
        lines.append("   :maxdepth: 1")
        lines.append("")
        for stem, _ in members:
            lines.append(f"   {stem}")
        lines.append("")
        (section_dir / "index.rst").write_text("\n".join(lines), encoding="utf-8")


def _on_builder_inited(app) -> None:
    generate(app)


def setup(app):
    app.connect("builder-inited", _on_builder_inited)
    return {"version": "0.2", "parallel_read_safe": True, "parallel_write_safe": True}


# Allow running directly (e.g. ``python docs/_ext/proto_docgen.py``).
if __name__ == "__main__":
    generate()
    print(f"Wrote generated fragments to {_OUT_DIR}")
